// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code

using TechTalk.SpecFlow;

#pragma warning disable

namespace AdminView.Tests.Specs
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
    public partial class AddANewUserFeature
    {
        private static TechTalk.SpecFlow.ITestRunner testRunner;

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            var featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"),
                "Add a new User",
                "In order to add a new user \r\nAs an administrator\r\nI want to be able to add a new " +
                "User", ProgrammingLanguage.CSharp, new string[]
                {
                    "ignore",
                    "admin"
                });
            testRunner.OnFeatureStart(featureInfo);
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null)
                 && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Add a new User")))
            {
                FeatureSetup(null);
            }
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add a new user with read permission")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Add a new User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("admin")]
        public virtual void AddANewUserWithReadPermission()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new user with read permission",
                ((string[]) (null)));
#line 8
            this.ScenarioSetup(scenarioInfo);
#line 9
            testRunner.Given("I am on the users page", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "Given ");
#line 10
            testRunner.When("I press \"Lägg till ny användare\"", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)),
                "When ");
#line 11
            testRunner.And("I enter \"Lucas@Textilgallerian.se\" in the \"Email\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 12
            testRunner.And("I have entered \"password\" in the \"Password\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 13
            testRunner.And("I have entered \"password\" in the \"PasswordConfirmation\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 14
            testRunner.And("I have selected \"läsa\" in the \"Role\" dropdown", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 15
            testRunner.Then("the system should present \"Användaren har skapats\"", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "Then ");
#line 16
            testRunner.And("a user with email \"Lucas@Textilgallerian.se\" and password \"password\" should exist" +
                           "", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 17
            testRunner.And("the user \"lucas@textilgallerian.se\" should have the role \"läsa\"", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add a new user with update permission")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Add a new User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("admin")]
        public virtual void AddANewUserWithUpdatePermission()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new user with update permission",
                ((string[]) (null)));
#line 19
            this.ScenarioSetup(scenarioInfo);
#line 20
            testRunner.Given("I am on the users page", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "Given ");
#line 21
            testRunner.When("I press \"Lägg till ny användare\"", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)),
                "When ");
#line 22
            testRunner.And("I enter \"Per@Textilgallerian.se\" in the \"Email\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 23
            testRunner.And("I have entered \"secure\" in the \"Password\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 24
            testRunner.And("I have entered \"secure\" in the \"PasswordConfirmation\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 25
            testRunner.And("I have selected \"redigera\" in the \"Role\" dropdown", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 26
            testRunner.Then("the system should present \"Användaren har skapats\"", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "Then ");
#line 27
            testRunner.And("a user with email \"Per@Textilgallerian.se\" and password \"secure\" should exist",
                ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 28
            testRunner.And("the user \"per@textilgallerian.se\" should have the role \"redigera\"", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute(
            "Add a new user with invalid password confirmation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Add a new User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("admin")]
        public virtual void AddANewUserWithInvalidPasswordConfirmation()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new user with invalid password confirmation",
                ((string[]) (null)));
#line 30
            this.ScenarioSetup(scenarioInfo);
#line 31
            testRunner.Given("I am on the users page", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "Given ");
#line 32
            testRunner.When("I press \"Lägg till ny användare\"", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)),
                "When ");
#line 33
            testRunner.And("I enter \"Emil@Textilgallerian.se\" in the \"Email\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 34
            testRunner.And("I have entered \"password\" in the \"Password\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 35
            testRunner.And("I have entered \"secure\" in the \"PasswordConfirmation\" field", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 36
            testRunner.And("I have selected \"admin\" in the \"Role\" dropdown", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 37
            testRunner.Then("the system should present \"Lösenordsbekräftelsen stämmer inte\"", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "Then ");
#line 38
            testRunner.And("no user with email \"Emil@Textilgallerian.se\" should exist", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add a new user when not beeing admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Add a new User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("admin")]
        public virtual void AddANewUserWhenNotBeeingAdmin()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new user when not beeing admin",
                ((string[]) (null)));
#line 40
            this.ScenarioSetup(scenarioInfo);
#line 41
            testRunner.Given("I am signed in as an user with role \"redigera\"", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "Given ");
#line 42
            testRunner.And("I am on the users page", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 43
            testRunner.When("I am on the users page", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "When ");
#line 44
            testRunner.Then("the link \"Lägg till ny användare\" should be missing", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}

#pragma warning restore

#endregion