using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.Entities
{
    /// <summary>
    /// Base class for discount coupons
    /// </summary>
    public abstract class Coupon
    {
        /// <summary>
        /// The code for this coupon
        /// (auto-generated by default)
        /// </summary>
        public String Code { get; set; }

        /// <summary>
        /// When the coupon should start to be valid
        /// </summary>
        public DateTime Start { get; set; }
        // End is set to null if Unlimited time
        
        /// <summary>
        /// When the coupon should end
        /// Optional, can last forever
        /// </summary>
        public DateTime? End { get; set; }
        
        /// <summary>
        /// Which customers is this coupon valid for
        /// If coupon is for all customers it should be set to null
        /// </summary>
        public List<Customer> CustomersValidFor { get; set; }
        
        /// <summary>
        /// Which users have used this coupon
        /// </summary>
        public List<Customer> CustomersUsedBy { get; set; }

        /// <summary>
        /// Max amount of times that a customer is allowed to use the coupon
        /// </summary>
        public int UseLimit { get; set; }

        /// <summary>
        /// Boolean deciding if the coupon can be combined
        /// with other coupons
        /// </summary>
        public bool CanBeCombined { get; set; }

        /// <summary>
        /// Abstract method for determine if the Cart
        /// sent in is valid for this Coupon
        /// </summary>
        /// <param name="cart"></param>
        /// <returns>Boolean</returns>
        public abstract Cart IsValidFor(Cart cart);
    }
}
